format = """
$directory\
$git_branch\
$git_state\
$git_status\
$line_break\
$character"""

right_format = """
$cmd_duration
$python
$jobs
$hostname
"""

palette = "catppuccin_mocha"

add_newline = false
command_timeout = 1000
scan_timeout = 10000
[fill]
symbol = " "

[directory]
style = "blue"

[character]
success_symbol = "[❯](mauve)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "[ $branch]($style)"
style = "flamingo"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "rosewater"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "flamingo"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
symbol = '󰌠'
style = "peach"
format = "[$symbol $virtualenv]($style) "

[jobs]
symbol = ' '
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[hostname]
ssh_only = false
format =  "[@$hostname ](sapphire)"
trim_at = ".deneb.group"
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
