[[language]]
name = "lua"
language-servers = ["lua-language-server"]
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright", "ruff"]
auto-format = true

[language-server.lua-language-server]
command = "lua-language-server"

[language-server.pyright]
command = "pyright"
args = ["--stdio"]

[language-server.ruff]
command = "ruff"
args = ["server"]
